### ISSUE TITLE
Function to download collisions data

### ISSUE THREAD

**Issue by Robinlovelace** [cyclestreets/cyclestreets-r#10]
I'm confident this is the next most useful function after journey. @mvl22 and @EricKrg please input and if you get a chance. Note I've created a boilerplate script in #9 that needs filling. Contributions very welcome!

**Comment by Robinlovelace** [comment]
Closing for now as out of scope and stale.

**Comment by mvl22** [comment]
Also there's a separate Stats19 R package which is probably better to use anyway in an R context.
