### ISSUE TITLE
Submit for peer review

### ISSUE THREAD

**Issue by Robinlovelace** [cyclestreets/cyclestreets-r#11]
To https://github.com/ropensci/onboarding/issues/ I suggest. Happy with this @mvl22 and @EricKRG ?

**Comment by Robinlovelace** [comment]
Not a priority. @mvl22 now this has been incorporated into the cyclestreets org are you/Simon up for auditing it, or at least taking a read of the documentation? https://rpackage.cyclestreets.net/

**Comment by mvl22** [comment]
Yeah, didn't spot any errors.

**Comment by mvl22** [comment]
Be good to have a short blog post from you about the package :)
