### ISSUE TITLE
Missing features from stplanr

### ISSUE THREAD

**Issue by mem48** [cyclestreets/cyclestreets-r#12]
The old function `stplanr::route_cyclestreet` could return grouped data (one row per route) and derived values cum_hill change_elev dif_max_min up_tot down_tot av_incline co2_saving calories busyness

The new function` cyclestreets::journey` does not group (one row per route segment), and cannot calculate these grouped values.

This seems like a limitation and makes the cyclestreet package less useful.

**Comment by Robinlovelace** [comment]
Good points. Will be good if we can get XYZ linestrings in there. Is it working yet in **opentripplanner**?

**Comment by mem48** [comment]
Yes the relevant code is

```
polyline2linestring <- function(line, elevation = NULL){
  line <- gepaf::decodePolyline(line)
  line <- as.matrix(line[,2:1])
  if(exists("elevation")){
    # Some modes don't have elevation e.g TRANSIT, check for this
    if(all(is.na(elevation))){
      ele <- rep(0,nrow(line))
    }else{
      elevation <-elevation[order(elevation$distance),]
      # Calculate the length of each segment
      dist <-sapply(seq(1,nrow(line)-1),function(x){geosphere::distm(line[x,], line[x+1,], fun = geosphere::distHaversine)})
      dist <- cumsum(dist)
      vals <- findInterval(dist, elevation$distance)
      vals[vals == 0] = 1L
      ele <- elevation$second[c(1,vals)]
    }
    linestring3D <- cbind(line, ele)
    linestring3D <- sf::st_linestring(linestring3D, dim = "XYZ")
    return(linestring3D)
  }else{
    linestring <- sf::st_linestring(line)
    return(linestring)
  }

}
```

Fo cyclestreets the inputs will be different OTP returns [Google Polyline Beans ](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) and then provides the elevation data also in an odd format so much of this function is dealing with that.

For cyclestreets really key bits are making a 2 X N or 3 x N matrix of coordinates and then letting SF do the rest

```
if(elevation){
 linestring3D <- cbind(line, ele)
    linestring3D <- sf::st_linestring(linestring3D, dim = "XYZ")
    return(linestring3D)
  }else{
    linestring <- sf::st_linestring(line)
    return(linestring)`
}
```

**Comment by Robinlovelace** [comment]
Great. Many thanks.

**Comment by Robinlovelace** [comment]
Closing for now as we have some additional columns calculated 'in house'. We don't want to add too many extra variables though as outlined in #19. Feel free to re-open, this issue hasn't been touched in 3 years so doesn't seem there's much demand.
