### ISSUE TITLE
Move to cyclestreets github org

### ISSUE THREAD

**Issue by Robinlovelace** [cyclestreets/cyclestreets-r#20]
- [ ] Update urls in documentation
- [x] Move across!

I think this is a great idea proposed by @mvl22, should lead to tighter CycleStreets integration and help us fix issues with expertise from the cyclestreets team ; )

**Comment by Robinlovelace** [comment]
@mvl22 can you delete the repo you created? Suggested workflow: rename the repo here then transfer. Source: https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by mvl22** [comment]
Ah, yes sorry that makes sense now.

I've deleted that. Will you be happy with the target name `cyclestreets-r`? We already have a repo called 'cyclestreets' and cyclestreets-r is nice and self-explanatory. I see that:

"The target account must not have a repository with the same name, or a fork in the same network."

I've invited you as an organisation member, so if you accept that I can then add privileges for you to create a repo which sounds like is needed.

**Comment by Robinlovelace** [comment]
Renamed. Are you up for changing the URLs @mvl22 and then we can shift this thing!

**Comment by mvl22** [comment]
> Are you up for changing the URLs @mvl22

I'm not quite sure what you mean. Basically I think you need to initiate the change at your end:

"When you transfer a repository that you own to another user account, the new owner will receive a confirmation email."

So the process now is just:

1) You accept the invite to join the CycleStreets organisation (welcome!) - let me know when you have.
2) I promote your rights to add repo creation.
3) You push it over as per their documentation.

**Comment by Robinlovelace** [comment]
No I meant changing the URLs in the documentation. Will try to transfer the repo now in any case.

**Comment by Robinlovelace** [comment]
>     1. let me know when you have.

Just joined.

And yes you're right about needing to promote my rights.

![image](https://user-images.githubusercontent.com/1825120/114229392-ad216a80-996f-11eb-98c2-a775d479f5e6.png)

**Comment by mvl22** [comment]
> And yes you're right about needing to promote my rights.

OK, that's now done. I think you should now be able to do it.

Let me know when that's all done.

**Comment by Robinlovelace** [comment]
Job done, can you add a team and make me admin of it, with control over this repo and contributors in case they need adding.

![image](https://user-images.githubusercontent.com/1825120/114231064-d80cbe00-9971-11eb-8226-6f9db3d33dde.png)

**Comment by mvl22** [comment]
> Job done, can you add a team and make me admin of it, with control over this repo and contributors in case they need adding.

I think that's done - have e-mailed fuller details but you're set as an admin of that repo so should have full control.

**Comment by Robinlovelace** [comment]
> I think that's done - have e-mailed fuller details but you're set as an admin of that repo so should have full control.

Great. I think the only remaining task is: 

>  Update urls in documentation

Which are actually pretty minimal:

```
rg 'robinlovelace/cyclestreets'                                            
README.md
3:[![R-CMD-check](https://github.com/robinlovelace/cyclestreets/workflows/R-CMD-check/badge.svg)](https://github.com/robinlovelace/cyclestreets/actions)

README.Rmd
6:  [![R-CMD-check](https://github.com/robinlovelace/cyclestreets/workflows/R-CMD-check/badge.svg)](https://github.com/robinlovelace/cyclestreets/actions)
```

A bigger issue is the package's auto-generated documentation. The package website used to be hosted at http://robinlovelace.github.io/cyclestreets like https://robinlovelace.github.io/sfextras/ is. Can you set up gh pages for this org @mvl22 or publish the contents of https://github.com/cyclestreets/cyclestreets-r/tree/gh-pages in some other way?

**Comment by Robinlovelace** [comment]
Update: I've re-published the site at https://robinlovelace.github.io/cyclestreets/

Would be great to have the package docs hosted at r-package.cyclestreets.net, cyclestreets.net/r-package or similar and then we can link to those auto-updating documentation pages as the package evolves.

**Comment by mvl22** [comment]
Now at:

https://rpackage.cyclestreets.net/

:)

**Comment by Robinlovelace** [comment]
:tada:

**Comment by Robinlovelace** [comment]
> Now at:
> 
> https://rpackage.cyclestreets.net/
> 
> :)

Another question @mvl22: how long does it take to update, 5 minutes after commits to the `gh-pages` branch (have just pushed to test it ~5 minutes ago and nothing yet).

**Comment by Robinlovelace** [comment]
Good news, it's updated.

**Comment by mvl22** [comment]
> how long does it take to update

I don't know, that's presumably whatever Github has decided.
