### ISSUE TITLE
Short segments

### ISSUE THREAD

**Issue by Robinlovelace** [cyclestreets/cyclestreets-r#22]
As reported by @natesheehan: 

Currently, very short routes do not work with the `journey` function. 

Error:
`Error in stats::filter(x, rep(1/n, n), sides = 2) : 
  'filter' is longer than time series`
Example:
```r
# dput(desire_line_town) getting lat long
origin = c(-0.214849749698027,51.5586119006974)
destination = c( -0.214888955159809,51.5564466729046)

a = cyclestreets::journey(
  origin,
  destination 
)
#> Loading required namespace: stplanr
#> Error in stats::filter(x, rep(1/n, n), sides = 2): 'filter' is longer than time series
mapview::mapview(a)
#> Error in eval(quote(list(...)), env): object 'a' not found
Created on 2021-05-19 by the reprex package (v2.0.0)
```

From the old cyclestreets repo...

**Comment by Robinlovelace** [comment]
I can reproduce the issue.

**Comment by mvl22** [comment]
Works on the site:
https://www.cyclestreets.net/journey/74610407/

Are the co-ordinates the right way round? Your note says "lat long" but the order shown is lon, lat.

PS Be aware that exceptionally short routes (<4m) will not work, as <4m is basically a sign of people making errors:
"Journey lengths must be at least 4 metres, and not more than 300 km."
https://www.cyclestreets.net/api/v1/journey/

**Comment by Robinlovelace** [comment]
It's an issue with our R code not your service Martin. Cheers for checking it out in any case. Here's the output with verbose mode on:

``` r
origin = c(-0.214849749698027,51.5586119006974)
destination = c( -0.214888955159809,51.5564466729046)

a = cyclestreets::journey(
  silent = FALSE,
  origin,
  destination 
)
#> [1] "The request sent to cyclestreets.net was: https://www.cyclestreets.net/api/journey.json?key=,key.&itinerarypoints=-0.214849749698027%2C51.5586119006974%7C-0.214888955159809%2C51.5564466729046&plan=fastest&reporterrors=1"
#> Loading required namespace: stplanr
#> Error in stats::filter(x, rep(1/n, n), sides = 2): 'filter' is longer than time series
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Robinlovelace** [comment]
Closed in https://github.com/cyclestreets/cyclestreets-r/pull/24
