### ISSUE TITLE
clientRouteId removed from API

### ISSUE THREAD

**Issue by mem48** [cyclestreets/cyclestreets-r#43]
Causing routing failure FYI @Robinlovelace @mvl22

**Comment by mvl22** [comment]
Hmm, I'm surprised this would cause any breakage. We removed this bogus API field, but assumed that clients wouldn't be reading it anyway.

Can you just remove all references to it? You presumably aren't using it as it doesn't return any useful data.

**Comment by Robinlovelace** [comment]
We will. Tracking the issue here.

**Comment by mvl22** [comment]
Great; thanks for that. Sorry this caused a blip!
