### ISSUE TITLE
Batch should auto-remove job after CSV download

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclestreets-r#48]
There is now an API call to remove the batch (including all data) rather than having it left lying about.

https://www.cyclestreets.net/api/v2/batchroutes.deletejob/

This should be added into the `batch` function, used after a successful CSV download.

**Comment by Robinlovelace** [comment]
Minimal test batch created, let's see if I can delete it as a test of this new functionality:

![image](https://user-images.githubusercontent.com/1825120/219800671-dc6bf603-7385-4ba8-b1dd-95bc76a5f33c.png)

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 it fails as follows:

```
Response [https://api.cyclestreets.net/v2/batchroutes.createjob?key=5b44de2e26338760]
  Date: 2023-02-17 21:59
  Status: 200
  Content-Type: application/json; charset=UTF-8
  Size: 77 B
{
    "error": "The name parameter is required, but has not been supplied."
```

Do you need to replace `name` with `username` in your code?

**Comment by Robinlovelace** [comment]
Success! As I suspected, passing both `name` and `username` fixed it.

![image](https://user-images.githubusercontent.com/1825120/219802552-f1131ca1-afde-4170-a9af-d2aab89953a6.png)

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 re-opening due to this error:

```
The geometry parameter is required, but has not been supplied.
```

**Comment by mvl22** [comment]
> Response [https://api.cyclestreets.net/v2/batchroutes.createjob?key=xxx]
> ...
> Do you need to replace name with username in your code?

Your example was using `batchroutes.createjob` not `batchroutes.deletejob` ...

`batchroutes.deletejob` definitely does not reference any name parameter, and that should be removed from your code.

**Comment by mvl22** [comment]
> The geometry parameter is required, but has not been supplied.

That parameter is only present in `batchroutes.createjob`. Please check your code is using the correct API call.
