### ISSUE TITLE
Cannot delete jobs that are 'finalising'

### ISSUE THREAD

**Issue by Robinlovelace** [cyclestreets/cyclestreets-r#58]
This may be more of a CycleStreets issue than a cyclestreets-r issue but reporting here in any case. Any ideas how to delete the job shown below @mvl22 ?

![image](https://user-images.githubusercontent.com/1825120/228142142-a1f600d5-dafe-4120-8e39-b4b3f816b6cd.png)

**Comment by mvl22** [comment]
We need to add a configuration option for whether a job should or shouldn't be commissioned if it doesn't meet quality control. At present the system assumes it is desirable for job problems to result in an active fail that needs investigatory intervention; other times it is preferable for failures to be tolerated if the client devs are active about checking for issues.

**Comment by mvl22** [comment]
> We need to add a configuration option for whether a job should or shouldn't be commissioned if it doesn't meet quality control. At present the system assumes it is desirable for job problems to result in an active fail that needs investigatory intervention; other times it is preferable for failures to be tolerated if the client devs are active about checking for issues.

Please see #86.

> This may be more of a CycleStreets issue than a cyclestreets-r issue but reporting here in any case. Any ideas how to delete the job shown below?

Once the above implemented in the R package and client users (and other non-R users) have migrated, we will implement hard failures so that jobs are no longer left in finalisation.
