### ISSUE TITLE
Reduce waiting time in batch()

### ISSUE THREAD

**Issue by Robinlovelace** [cyclestreets/cyclestreets-r#66]

**Comment by mvl22** [comment]
Is this polling time for results? Or wait time between requests? If the latter, I would just get rid of it.

**Comment by Robinlovelace** [comment]
It's how long to wait before it asks for the data back. After that it asks for the data every 10s: 

https://github.com/cyclestreets/cyclestreets-r/blob/86901c4e0776c12b3fda0e2cea5805a75ed16b31/R/batch.R#L157-L163

Open to suggestions of better ways to do this..
