### ISSUE TITLE
Reduce size of GeoJSON files uploaded for batch routing

### ISSUE THREAD

**Issue by Robinlovelace** [cyclestreets/cyclestreets-r#74]
Currently we upload files with the full data of the input, 15 dp coordinates and other non-geographic attributes.

**Comment by mvl22** [comment]
Just to note that these two recommendations (to remove extraneous properties and trim co-ordinates to 5dp) are now documented on the API page and included within the API error response.

https://www.cyclestreets.net/api/v2/batchroutes.createjob/
