### ISSUE TITLE
Github repo location

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclestreets-r#8]
Any chance we might have this instead as an official repo at

cyclestreets/cyclestreets-r

instead of

Robinlovelace/cyclestreets

? Would be great to have such officialness, and we are aiming to put other wrapper-type stuff there over time.

**Comment by Robinlovelace** [comment]
Sure but it will be easier to find and install if it's called cyclestreets. 2 alternative suggestions:

- Submit it for peer review on RopenSci
- Put it as a subfolder in a metarepo called 'wrappers' or 'interfaces' or something

Of those I prefer the the 1st option for various reasons including exposure and the benefits of peer review of the code.

**Comment by Robinlovelace** [comment]
Fixed.
